# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.CharField(max_length=100)),
                ('requestorname', models.CharField(max_length=100)),
                ('requesteddate', models.DateField(blank=True, default=datetime.date(2018, 10, 26))),
                ('projectname', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('processoverview', models.CharField(blank=True, max_length=1000)),
                ('excepted_TAT', models.DateTimeField(blank=True)),
                ('requestormanagername', models.CharField(max_length=100)),
                ('requestormanagermailid', models.CharField(max_length=100)),
                ('requestormailid', models.CharField(max_length=100)),
                ('pocmailid', models.CharField(max_length=100)),
            ],
        ),
    ]
