# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='pocmailid',
        ),
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='request',
            name='requestorempid',
            field=models.CharField(default=2002, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default=2334, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='processoverview',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='request',
            name='requesteddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
