# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20181026_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestid',
            field=models.CharField(max_length=11),
        ),
    ]
