# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20181028_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
